org.gradle.jvmargs=-Xmx3G

minecraft_version=26.1.2

archives_base_name=observable
mod_version=5.5.0
release_channel=beta
maven_group=observable

architectury_version=20.0.9

fabric_loader_version=0.19.3
fabric_api_version=0.154.2+26.1.2

neoforge_version=26.1.2.81

curseforge_id=509575
modrinth_id=VYRu7qmG
